name: Build and release
on:
  workflow_dispatch:
  push:
    branches: ['main']
jobs:
  build:
    name: Build and release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      # - name: Install dependencies
      #   run: go get .
      - name: Build
        run: make
      - name: Release if running on main
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
